let canvas, ctx, dsc=1, isPortrait=false;
let ST='LOADING';
let imgs={bg:{},ch:{}};
let ldn=0, tot=0, lastT=0;
let pl, en, pt;
let bgO, curBG, bgCT, gspd, wave, sc, spT, dst;
let selC='warrior', saf, sat;
let goT=0;
let xp=0, gold=100, plLv=1, navTab='game', curLoc=0;
let totalKills=0, gamesPlayed=0, bestScore=0, bestWave=1;
